### ISSUE TITLE
Suggestion: consider scikit-lern like pipelines

### ISSUE THREAD

**Issue by MrLoh** [hadley/modelr#17]
I'm a big fan of the tidyverse approach and recently came across this package. I also recently played around a bit with feature extraction and model pipelines in scikit-learn. There's a good introduction [here](http://zacstewart.com/2014/08/05/pipelines-of-featureunions-of-pipelines.html). 

I think this kind of approach would fit very well with the tidyverse philosophy, maybe it's a good source of inspiration. 

I'm excited to try this package out more. It's a good step towards a more systematic machine learning approach for R, that is desperately needed — caret is also a good step into that direction of course.

**Comment by hadley** [comment]
Probably not in this package, but it's definitely on my long term to do list
