### ISSUE TITLE
README.md?

### ISSUE THREAD

**Issue by dtelad11** [hadley/modelr#26]
I have very little experience interacting with github projects, so apologies if this is the wrong channel.

I couldn't find any modelr documentation, I'm guessing that the package is too young for that -- would it be beneficial if I flesh out README.md a bit? I'm not sure what's the etiquette for becoming a contributor on such a project. Thanks!

**Comment by hadley** [comment]
The documentation is basically in http://r4ds.had.co.nz/model-basics.html and related chapters.  A brief summary for the readme would be great!

**Comment by dtelad11** [comment]
Thanks. See #28.
