### ISSUE TITLE
Should add preds/resids produce long form?

### ISSUE THREAD

**Issue by hadley** [hadley/modelr#3]

**Comment by hadley** [comment]
@lionel- have you thought about this at all?  It my use, it seems like the long form is going to be most useful, and it does generalise to multiple datasets in a more straightforward way.

**Comment by lionel-** [comment]
hmm what do you mean by long form?

**Comment by hadley** [comment]
Currently `add_predictions()` adds one column per model, but that makes it hard to plot multiple models at the same time. Typically I do a `gather(model1:model10, model, prediction)` afterwards

**Comment by lionel-** [comment]
The long form would also be more useful to me as I would only use those quantities in plots. But maybe other people would prefer to have residuals on their own columns as it would make it easier to perform tests? I never do such tests so I don't know really.

Could we have two kinds of verbs? e.g. `add_predictions()` and `gather_predictions()`?

**Comment by hadley** [comment]
Maybe `spread_predictions()` and `gather_predictions()`? That's not too awful.

**Comment by lionel-** [comment]
I think I prefer `add_` but yes, that's not too awful ;)

**Comment by lionel-** [comment]
The following prefix taxonomy could work nicely across packages: `add_` for adding a single column, e.g. the defunct `add_rownames()` and `spread_` for multiple columns.

**Comment by hadley** [comment]
Yeah, and in this case `add_predictions()` could automatically derive the name of the response variable from the model, so (e.g.) adding predictions from `lm(mpg ~ wt, data = mtcars)` would add a column called `mpg`. That's the most useful default if you want to overlay predictions from a model on to a plot of the data set.

**Comment by lionel-** [comment]
> add_predictions() could automatically derive the name of the response variable from the model

Good idea, though it probably should qualify it with a prefix or suffix, like `mpg_fit` or `mpg_pred`, so it doesn't overwrite `mpg`.

**Comment by hadley** [comment]
Oh hmmmm, I think about using adding predictions to a grid, but you're right that people do also add them to the original dataset

**Comment by lionel-** [comment]
yes it's very useful for model checking to plot the original data (or a summary of it) alongside the predictions.

**Comment by hadley** [comment]
How about this hierarchy?

* `resid()` and `predict()` are the base "scalar" functions: they take a data frame and a model and return a vector. (We may want to have `residuals()` and `predictions()` wrappers around these so we can provide better defaults across packages)

* `add_residuals()` and `add_predictions()` are "data frame" versions of `resid()` and `predict()` they return a modified data set with one extra column

* `gather_predictions()`, `gather_residuals()`, `spread_residuals()` and `spread_predictions()` are "map2" versions of `add_residuals()` and `add_predictions()`. They take either a model or a list or models, and a data frame or a list of data frames. They are vectorised the same way as `map2()` and return a new data frame either with multiple columns or multiple rows. They could potentially have an `expand` argument which if both were lists would compute the full cross-product.

    (Taking either a data frame or list of data frames might be a bit tricky, but I think it's better than the alternative of either requiring an explicit `list()` or having even more variants of the functions).

**Comment by lionel-** [comment]
> Taking either a data frame or list of data frames might be a bit tricky

`purrr::splice()` should do the trick.

> a data frame or a list of data frames [...] and return a new data frame either with multiple columns or multiple rows.

How would it work? `bind_rows()` the input data frames and then then spread or gather the resids/preds for each model?

> We may want to have residuals() and predictions() wrappers around these so we can provide better defaults across packages

That'd be nice, the interface of `predict()` is a bit clunky. Should they always return data frames, with intervals as columns?

**Comment by hadley** [comment]
Either `bind_rows()` or possibly work on purrr to add `map_dfr()` and `map_dfc()` (or maybe `map_row()` & `map_col()`.

I wonder if we should have `predict()` and `predict_ci()`?

**Comment by lionel-** [comment]
> Either bind_rows() or possibly work on purrr to add map_dfr() and map_dfc() (or maybe map_row() & map_col().

I think I prefer `map_df(.dir = "cols")`, with `"rows"` being the default. It seems easier to grasp.

> I wonder if we should have predict() and predict_ci()?

Maybe a more general `predict_q()` with default `quantiles = c(0.025, 0.975)`? This one should return a data frame for sure. But in general it's not clear which functions should be scalar and which should be dataframe valued. Probably easiest to have them all return a data frame. In any case we definitely should avoid the type instability of some `stats::` functions.

**Comment by hadley** [comment]
Let's discuss that one in purrr: mostly I don't like the lack of symmetry if you provide a default value for `.dirs` - you'd have `map_df(...)` and `map_df(... .dir = "rows")`.

I think this modelr should mostly provide data frame interfaces to the outside. But it seems like vector/scalar interfaces are often easier to compose internally. And I'm a bit concerned that implies that the data frame interface might be too opinionated - i.e. it's really helpful if you stick exactly to our vision, but not very helpful if you're doing something differently. We may need to think about providing both high and low level apis.

**Comment by lionel-** [comment]
```r
pred_quantiles <- function(...) {
  dots <- list(...)
  if (!length(dots)) {
    dots <- list(lower = 0.025, upper = 0.975)
  }
  *etc*
}
```

And then we can provide named quantiles and get a data frame with the corresponding names: `pred_quantiles(median = 0.5, upper = 0.75)`

**Comment by lionel-** [comment]
I think `map_dfc()` and `map_dfr()` are a bit cryptic. `map_row()` seems like it's about the input rather than the output (mapping rows rather than row-binding the output).

Maybe `map_rbind()` and `map_cbind()`?

> But it seems like vector/scalar interfaces are often easier to compose internally. And I'm a bit concerned that implies that the data frame interface might be too opinionated

Great points. Maybe provide `_v()` suffixed versions, as in early versions of purrr?

**Comment by hadley** [comment]
Added `add_predictions()`, `gather_predictions()` and `spread_predictions()` just so I can finish the chapters in R4ds. But let's keep thinking about this
