### ISSUE TITLE
Using map for double output

### ISSUE THREAD

**Issue by tchakravarty** [hadley/modelr#30]
@hadley, thanks for an excellent new addition to the `tidyverse` suite of packages & looking forward to the book. 

I have just begun using the package, and have come across some behaviour that I find non-intuitive and wanted to check if this was by design.

I am trying to train and test models across k-fold cross-validation sets like so: 

```{r}
library(tidyverse)
library(modelr)

# simulate some data
df_foo = data_frame(
  y = rnorm(1000),
  x = rnorm(1000)
)

# build models across CV sets
cv_foo = df_foo %>% 
  crossv_kfold(k = 10) %>% 
  mutate(
    # create the model for each cross-validation set
    model_1 = map(train, .f = function(train_data) {
      lm(y ~ x, data = train_data)
    }),
    
    # create the predictions for each cross-validation set
    prediction_train_1 = map(model_1, predict),
    prediction_test_1 = map2(model_1, test, predict),
    
    # get the accuracy on the cross-validation set
    # accuracy_train_1 = mae(model = model_1, data = train),
    accuracy_train_1 = map2(model_1, train, mae),
    accuracy_test_1 = map2(model_1, test, mae)
  )
```

Two questions: 
 
- Should not `mae` work directly as in the commented line: `mae(model = model_1, data = train)`?

- I am fine with using `map` to pass arguments to `mae` in this context, but then given that the return is a `double` (with no additional class information), should it not be added as a `vector` to the `tibble` and not as a `list` of `double`s? I am sure that you do not want to get into maintaining a coercing hierarchy of types, but in this case, I would just expect a column of accuracy measurements that I can easily visually scan.

It takes a further `%>% 
  mutate(
    accuracy_train_1 = purrr::as_vector(accuracy_train_1)
  )` to get what I want.

**Comment by hadley** [comment]
`mae()` is not yet vectorised, so you'll need to use `map2()` in the interim. But you want a vector double vector, not a list, so you should use `map2_dbl()`.
