### ISSUE TITLE
response.default function for models without a terms component?

### ISSUE THREAD

**Issue by bgreenwell** [hadley/modelr#4]
I work with models that don't usually contain a terms component (e.g., decision trees from rpart). Though not all models contain a formula comnponent, I usually extract the response from the model formula:

```{r}
#' @export
response.default <- function(model, data) {
  var <- formula(model)[[2L]]
  eval(var, data)
}
```

This should also still work when the model formula contains a transformed response (e.g., `sqrt(y) ~ .`). Hope you find this useful.

**Comment by hadley** [comment]
Good idea - thanks!
