### ISSUE TITLE
Stupidly simple idea

### ISSUE THREAD

**Issue by Ironholds** [hadley/modelr#5]
What about a simple model() function to work around the problem with pipeline-based modeling where a lot of base modelling functions have `data` as the *second* argument?

So it'd be very apply like:

    model <- function(data, fun, ...){
        return(fun(data = data, ...))
    }

**Comment by lionel-** [comment]
I mainly work with named list of fitted models and use this pipe-friendly tool to fit them:

```{r}
#' @export
fit_formulas <- function(.data, .fitting_fun, .response, ...,
                         .args = list()) {
  rhss <- list(...)

  # Shadowing .data to avoid getting the whole raw SEXP structure in
  # the calls captured by the fitting function (which gets displayed
  # in print methods)
  .args$data <- quote(.data)

  lapply(rhss, function(rhs) {
    stopifnot(identical(environment(.response), environment(rhs)))
    formula <- call("~", .response[[2]], rhs[[2]])
    environment(formula) <- environment(.response)

    do.call(".fitting_fun", c(list(formula), .args))
  })
}
```

```{r}
disp_linear_fits <- mtcars %>% fit_formulas(lm, ~disp,
  additive = ~drat + hp,
  full = ~drat * hp
)

disp_hierarchical_fits <- mtcars %>% fit_formulas(lme4::lmer, ~disp,
  additive = ~drat + hp + (1 | cyl),
  full = ~drat * hp + (1 | cyl)
)
```

**Comment by hadley** [comment]
Oooh, nice!

**Comment by lionel-** [comment]
cool, I'll document and add it soonish :)

**Comment by hadley** [comment]
I'm not sure if there's a big win to keeping the response in a separate variable, although one option would be to take a list of models instead of a list of arguments, and have a helper function that made that list using a response and a list of predictor models.  That would make it a little nicer for (e.g.) `glm()` where you're always going to be supplying at least one argument (the `family`). 

Then you could also have a functions like `add_one()` and `drop_one()` that made a list of models given a base formula, and then either adding or dropping one variable in each case. (But that's probably hard to do correctly so we might want to not implement yet.

**Comment by lionel-** [comment]
> I'm not sure if there's a big win to keeping the response in a separate variable

I find it makes it easier to spot the differences between the models, and nicer to type as well.

> That would make it a little nicer for (e.g.) glm() where you're always going to be supplying at least one argument (the family).

Good point. I just had a wild idea: how about checking the argument names and using all those starting with a dot as arguments passed on to the fitting function (with the dot stripped out). I think that would feel natural and could be a useful idiom in many other cases. Then we could type e.g. `.family = binomial` with glm models.

> Then you could also have a functions like add_one() and drop_one() that made a list of models given a base formula

Yes, a list-based pipe-friendly alternative to `update()` is direly needed.

**Comment by hadley** [comment]
I think that idea might be too wild ;)  I think it will be a bit too hard for people to grasp what is happening.  I'd prefer to be explicit either with the list of models or the list of arguments.

**Comment by lionel-** [comment]
Also we could have `lst()` semantics so that we can refer to previously mentioned models and use formula-verbs:

```{r}
disp_linear_fits <- mtcars %>% fit_formulas(lm, ~disp,
  additive = ~drat + hp,
  controlled = add_predictors(additive, ~cyl, ~am),
  full = merge_formulas(additive, controlled) %>%
    add_interactions(order = c(2, 3))
)
```

**Comment by hadley** [comment]
Yes!

**Comment by lionel-** [comment]
One advantage to taking a list of formulas is that it makes it easy to reuse model specs:

```{r}
disp_formulas <- lst(
  additive = ~drat + hp,
  controlled = add_predictors(additive, ~cyl, ~am)
)

mtcars %>% fit_formulas(lm, disp_formulas)
mtcars %>% fit_formulas(lm, map(disp_formulas, add_predictors, ~(1 | cyl)))
```

Then maybe we can reexport `lst()`, possibly with another name such as `formulas()`. In that case it may be nicer to call the fitting verb `fit_with()`:

```{r}
#' @export
formulas <- tibble::lst

linear_disp_fits <- mtcars %>% fit_with(lm, formulas(
  additive = ~drat + hp,
  controlled = add_predictors(additive, ~cyl, ~am)
))
```

**Comment by hadley** [comment]
And formulas could have an option argument called `response`? If present, `formulas()` would add that as a response to every input.

**Comment by lionel-** [comment]
Good idea. Should it be an option or should it be the first argument?

```r
models <- formulas(~disp,
  additive = ~drat + hp,
  controlled = add_predictors(additive, ~cyl, ~am)
))
```

**Comment by lionel-** [comment]
@hadley Is it alright for modelr to depend on purrr? I'd like to use `reduce()`. `Reduce()` is a bit unwieldy since it doesn't allow additional arguments to be passed on to `f`.

**Comment by hadley** [comment]
Yes, definitely
